<h1>Auswählen Sie Speisen für 3, 4 oder 5 Tagen</h1>
<div id="product_option">
    <span>Bestimmten die Anzahl von Produkten</span>
    <select>
        <option value="5">5 Tage</option>
        <option value="4">4 Tage</option>
        <option value="3">3 Tage</option>
    </select></div>

<div id="product_diy_container">
    <table border="1">
        <?php echo $this->loadProductHtmlBySku(); ?>
    </table>
</div>
<script type="text/javascript">
// func for loading js container
require(['jquery', 'jquery/ui'], function($){
    jQuery(document).ready(function () {
//        alert(jQuery("#product_option select option:selected").val());
    });
});
</script>


