<?php ?>
<h1>Auswählen Sie Speisen für 3, 4 oder 5 Tagen</h1>
<div id="product_option">
    <span>Bestimmten die Anzahl von Produkten</span>
    <select>
        <option value="5">5 Tage</option>
        <option value="4">4 Tage</option>
        <option value="3">3 Tage</option>
    </select>
</div>

<div id="product_diy_container">
    <table border="1">
        <?php echo $this->loadProductHtmlBySku(); ?>
    </table>
    <hr /><center><button id="to_cart" class="action primary">In Warenkorb</button></center>
</div>
<script type="text/javascript">
    var order_container = {"amount":5, "var_1":"", "var_2":"", "var_3":"", "var_4":"", "var_5":""};
    var base_url = "<?php echo $this->getUrl(); ?>";
// func for loading js container
require(['jquery', 'jquery/ui'], function($) {
    jQuery(document).ready(function () {
//        var session = "<?php //echo $this->_customerSession; ?>//";
//        if(session.length == 0) {
            jQuery("#product_diy_container table tr").each(function () {
                var index = jQuery(this).attr('index');
                order_container["var_" + index] = jQuery(this).attr("sku");
            });
        console.log(order_container);
    });
    /*
     Add iframe to choose target product
     */
    jQuery(".diy_button").click(function () {
//        if (jQuery(this).hasClass('active')) {
//            jQuery(this).parent().find("div.list_container div.product_list").slideToggle();
//            return false;
//        }
//        var price_class = jQuery(this).attr('price_class');
//        var index = jQuery(this).attr('index');
//        var iframe = "<iframe class='variant_box' src='" + base_url + "menue/index/variant?class=" + price_class + "&index=" + index + "'" +
//            "width='900px' height='450px' style='display: none' />";
//        jQuery(this).parent().find("div.iframe_container").append(iframe);
//        jQuery(this).addClass('active');
        jQuery(this).parent().find("div.list_container div.product_list").slideToggle();
    });
    /*
     load html wrapper(Product Block) with customer option
     */
    jQuery("#product_option select").change(function () {
        var selected = jQuery(this).find("option:selected").val();
        if (selected == '5') {
            jQuery("#product_diy_container table tr").show();
            order_container.amount = 5;
            console.log(order_container);
        }
        if (selected == '4') {
            jQuery("#product_diy_container table tr[index='5']").hide();
            jQuery("#product_diy_container table tr[index='4']").show();
            order_container.var_5 = "";
            order_container.amount = 4;
            console.log(order_container);
        }
        if (selected == '3') {
            jQuery("#product_diy_container table tr[index='4'], #product_diy_container table tr[index='5']").hide();
            order_container.var_4 = "";
            order_container.var_5 = "";
            order_container.amount = 3;
            console.log(order_container);
        }
    });
    /*
     update json "order container" when loading new product
     */
    jQuery("tr[class*='price_class_']").attrchange({
        trackValues: true,
        callback: function (event) {
            var index = jQuery(this).attr('index');
            if(parseInt(index) > order_container.amount){
                return false;
            }
            order_container["var_" + index] = jQuery(this).attr("sku");
            console.log(order_container);
        }
    });
    /*
    read ordered products in order_container json and set in cart
     */
    jQuery("#to_cart").click(function () {
        var data_to_post = "";
        jQuery.each(order_container, function (key, value) {
            if((key == "amount") || (value == "")){return;}
            data_to_post = data_to_post + value + ",";
        });
        var postData = new FormData();
        postData.append("menu_orders", data_to_post);
        jQuery.ajax({
            type: "POST",
            url: base_url+"menue/index/cart",
            data: postData,
            contentType: false,
            processData: false,
            dataType: "text",
            success: function(data){
                if (confirm("Ihr Wochenmenu ist bereits auf Warenkorb gelegt. Wollen Sie auf Warenkorb gehen?")) {
                    window.location = base_url+"checkout/cart/";
                }
            }
        });
    });
    /*
     get params from user choosed to load new product in menu
     */
    jQuery("button.choose_variant").click(function () {
        var sku = jQuery(this).find("input.sku").val();
        var name = jQuery(this).find("input.name").val()
        var description = jQuery(this).find("input.description").val();
        var img = jQuery(this).find("input.img").val();
        var price = jQuery(this).find("input.price").val();
        var position = jQuery(this).find("input.menu_index").val();
        load_new_var_product(sku, name, description, price, img, position);
    });
    /*
    save tmp user choose in Session
     */
    jQuery(window).bind('beforeunload',function(){

        var data_to_post = "";
        jQuery.each(order_container, function (key, value) {
            if((key == "amount") || (value == "")){return;}
            data_to_post = data_to_post + value + ",";
        });
        var postData = new FormData();
        postData.append("user_choose", data_to_post);
        jQuery.ajax({
            type: "POST",
            url: base_url+"menue/index/Session",
            data: postData,
            contentType: false,
            processData: false,
            dataType: "text",
            success: function(data){}
        });
    });
});
    /*
     load new product in menu block
     */
    function load_new_var_product(sku, name, description, price, img, position) {
        require(['jquery', 'jquery/ui'], function($){
//             console.log(sku+" and "+name+" and "+description+" and "+price+" and "+img+" and "+position);
        var target_block = jQuery("tr[index='"+position+"']");
//            console.log(target_block.attr('index'));
            target_block.attr("sku",sku);
            target_block.find("td.img_container img").attr(
                {
                    src: img,
                    srcset: img,
                    alt: name
                });
            target_block.find("td.img_container h5").html(name);
            target_block.find("td.product_info div.product_content span").html(description);
            target_block.find("td.product_price span").html(price);
        });
        return true;
    }
</script>


