<h1 id="menu_week">Bestellen Sie Speisen für <b>die nächste Woche</b></h1>
<h1><center>
        <button class="gui_change_backwards" action="backwards" onclick="loadTargetGUI(this)">
            <b style="color: blue"><     </b>
        </button>
        <b id="order_date">
            <?php echo $this->getOrderDate(true)['begin'] ." Bis ". $this->getOrderDate(true)['end']; ?>
        </b>
        <button class="gui_change_forwards" action="forwards" onclick="loadTargetGUI(this)" style="display: none">
            <b style="color: blue">     ></b>
        </button>
</center></h1>
<div id="product_diy_container">
    <table border="1">
        <?php echo $this->loadProductHtmlBySku(); ?>
    </table>
    <hr /><center><button id="to_cart" class="action primary">In Warenkorb</button></center>
</div>
<script type="text/javascript">
    var order_container = {"amount": 0, "var_1":"", "var_2":"", "var_3":"", "var_4":"", "var_5":""};
    var gui_status = {status: 1};
    var ordered_menu = null;
    var base_url = "<?php echo $this->getUrl(); ?>";
// func for loading js container
require(['jquery', 'jquery/ui'], function($) {
    jQuery(document).ready(function () {
//        if(session.length == 0) {
            jQuery("#product_diy_container table tr").each(function () {
                var index = jQuery(this).attr('index');
                order_container["var_" + index] = jQuery(this).attr("sku");
                if(jQuery(this).attr("sku") === 'disable'){
                    order_container.amount = order_container.amount + 1;
                }
            });
        var customerId = '<?php echo $this->_customerSession->getCustomerId(); ?>';
        if(customerId === ""){
            $("button[class*='gui_change_']").hide();
        }
        console.log(order_container);
    });
    /*
     Add iframe to choose target product
     */
    jQuery(".diy_button").click(function () {
        jQuery(this).parent().find("div.list_container div.product_list").slideToggle();
    });
    /*
     update json "order container" when loading new product
     */
//    jQuery("tr[class*='price_class_']").attrchange({
//        trackValues: true,
//        callback: function (event) {
//            var index = jQuery(this).attr('index');
//            if(parseInt(index) > order_container.amount){
//                return false;
//            }
//            order_container["var_" + index] = jQuery(this).attr("sku");
//        }
//    });
    /*
    read ordered products in order_container json and set in cart
     */
    jQuery("#to_cart").click(function () {
        var data_to_post = "";
        jQuery.each(order_container, function (key, value) {
//            if((key == "amount") || (value == "")){return;}
            if(key == "amount"){return;}
            data_to_post = data_to_post + value + ",";
        });
        data_to_post = data_to_post.substring(0, data_to_post.length -1);
        var postData = new FormData();
        postData.append("menu_orders", data_to_post);
        console.log(data_to_post);
        jQuery.ajax({
            type: "POST",
            url: base_url+"index.php/menue/index/cart",
            data: postData,
            contentType: false,
            processData: false,
            dataType: "text",
            success: function(data){
                if (confirm("Ihr Wochenmenu ist bereits auf Warenkorb gelegt. Wollen Sie auf Warenkorb gehen?")) {
                    window.location = base_url+"checkout/cart/";
                }
            }
        });
    });
    /*
     get params from user choosed to load new product in menu
     */
    jQuery("button.choose_variant").click(function () {
        var sku = jQuery(this).find("input.sku").val();
        var name = jQuery(this).find("input.name").val()
        var description = jQuery(this).find("input.description").val();
        var img = jQuery(this).find("input.img").val();
        var price = jQuery(this).find("input.price").val();
        var position = jQuery(this).find("input.menu_index").val();
        load_new_var_product(sku, name, description, price, img, position);
    });
    /*
    save tmp user choose in Session
     */
//    jQuery(window).bind('beforeunload',function(){
//
//        var data_to_post = "";
//        jQuery.each(order_container, function (key, value) {
//            if((key == "amount") || (value == "")){return;}
//            data_to_post = data_to_post + value + ",";
//        });
//        var postData = new FormData();
//        postData.append("user_choose", data_to_post);
//        jQuery.ajax({
//            type: "POST",
//            url: base_url+"menue/index/Session",
//            data: postData,
//            contentType: false,
//            processData: false,
//            dataType: "text",
//            success: function(data){}
//        });
//    });
});
    /*
     load new product in menu block
     */
    function load_new_var_product(sku, name, description, price, img, position) {
        require(['jquery', 'jquery/ui'], function($){
//             console.log(sku+" and "+name+" and "+description+" and "+price+" and "+img+" and "+position);
        var target_block = jQuery("tr[index='"+position+"']");
//            console.log(target_block.attr('index'));
            target_block.attr("sku",sku);
            target_block.find("td.img_container img").attr(
                {
                    src: img,
                    srcset: img,
                    alt: name
                });
            target_block.find("td.img_container h5").html(name);
            target_block.find("td.product_info div.product_content span").html(description);
            target_block.find("td.product_price span").html(price);
        });
        return true;
    }

    function menuStatus(element) {
        require(['jquery', 'jquery/ui'], function($) {
            var currentStatus = $(element).hasClass('active');
            var currentIndex =  $(element).parent().parent().attr('index');
            if (currentStatus){
                if(order_container.amount >= 2){
                    return alert('Sie sollten ESSEN mindestens für drei Tage bestellen!');
                }
                order_container.amount = order_container.amount + 1;
                $(element).parent().parent().css("background-color", "grey");
                $(element).removeClass('active');
                $(element).css('background-color', 'green');
                $(element).html('Enable');
                $(element).parent().parent().find('td.product_info')
                    .find('button').first().html("<del>Austausch</del>").prop('disabled', true);
                $(element).parent().parent().find('td.product_info').find('div.list_container').hide();
                order_container['var_'+currentIndex] = 'disable';
                console.log(order_container);
            }else {
                order_container.amount = order_container.amount - 1;
                $(element).parent().parent().css("background-color", "white");
                $(element).css('background-color', 'white');
                $(element).addClass('active');
                $(element).html('Disable');
                $(element).parent().parent().find('td.product_info')
                    .find('button').first().html("Austausch").prop('disabled', false);
                $(element).parent().parent().find('td.product_info').find('div.list_container').show();
                order_container['var_'+currentIndex] = $(element).parent().parent().attr('sku');
                console.log(order_container);
            }
        });
    }
    
    function loadTargetGUI(element) {
        require(['jquery', 'jquery/ui'], function($) {
            var currentGuiStatus = gui_status.status;
            var currentAction = $(element).attr("action");
            if(currentAction === "forwards"){
                var newStatus = currentGuiStatus + 1;
            }else{
                var newStatus = currentGuiStatus - 1;
            }
            if(newStatus === 0){ // route to view the orders from the last week
                // save ordered menu before routing
                ordered_menu = $("#product_diy_container").html();
                $("#menu_week").html("Sie haben für <b>diese Woche</b> bestellt");
                $("#order_date").html("<?php echo $this->getOrderDate(false)['begin'] ." Bis ". $this->getOrderDate(false)['end']; ?>");
                $("button.gui_change_backwards").hide();
                $("button.gui_change_forwards").show();
                var postData = new FormData();
                postData.append("begin", "<?php echo $this->getOrderDate(false)['raw_begin']; ?>");
                postData.append("end", "<?php echo $this->getOrderDate(false)['raw_end']; ?>");
                $.ajax({
                    type: "POST",
                    url: base_url+"menue/index/order",
                    data: postData,
                    contentType: false,
                    processData: false,
                    dataType: "text",
                success: function(data){
                    var vDom = $("<html></html>").html(data);
                    var tableBody = vDom.find("table").html();
                    $("#product_diy_container").html("<table border='1'>"+tableBody+"</table>");
                }
                });
                gui_status.status = 0;
            }else if(newStatus === 1){ // route to view for the next week
                $("#menu_week").html("Bestellen Sie Speisen für <b>die nächste Woche</b>");
                $("#order_date").html("<?php echo $this->getOrderDate(true)['begin'] ." Bis ". $this->getOrderDate(true)['end']; ?>");
                $("#product_diy_container").html(ordered_menu);
                $("button.gui_change_backwards").show();
                $("button.gui_change_forwards").hide();
                gui_status.status = 1;
            }else{
                return false;
            }
        });
        }
</script>


