<h1 id="menu_week">Bestellen Sie Speisen für <b>die nächste Woche</b></h1>
<h3 id="goal_label"><?php echo $this->getNutritionGoalLabel()[1]; ?></h3>
<h1><center>
        <button class="gui_change_backwards" action="backwards" onclick="loadTargetGUI(this)">
            <b style="color: blue"><     </b>
        </button>
        <b id="order_date">
            <?php echo $this->getOrderDate(true)['begin'] ." Bis ". $this->getOrderDate(true)['end']; ?>
        </b>
        <button class="gui_change_forwards" action="forwards" onclick="loadTargetGUI(this)" style="display: none">
            <b style="color: blue">     ></b>
        </button>
</center></h1>
<div id="product_diy_container">
    <table id="diy_table" border="1">
        <?php echo $this->loadProductHtmlBySku(); ?>
    </table>
    <hr />
    <div id="side_dish_title" style="display: none">
        <button class="before" onclick="renderSideMenu(this)"><h4><b>Vorspeisen</b></h4></button>
        <button class="after" onclick="renderSideMenu(this)"><h4><b>Nachspeisen</b></h4></button>
    </div>
    <table id="before" border="1" style="display: none">
        <?php $before = $this->loadProductHtmlBySku(true, true); echo $before;?>
    </table>
    <table id="after" border="1" style="display: none">
        <?php
            $after = $this->loadProductHtmlBySku(true, false);
            echo $before === $after? '': $after;
        ?>
    </table>
    <hr />
    <center><button id="to_cart" class="action primary" onclick="weightValidate()">Weiter</button></center>
</div>
<script type="text/javascript">
    var order_container = {"amount": 0, "var_1":"", "var_2":"", "var_3":"", "var_4":"", "var_5":"",
        "var_6":"disable", "var_7":"disable", "var_8":"disable", "var_9":"disable", "var_10":"disable",
        "var_11":"disable", "var_12":"disable", "var_13":"disable", "var_14":"disable", "var_15":"disable"};
    var side_menu_status = {render: 'before', hide: 'after'};
    var week = {mon:[1,'Montag'],tue:[2,'Dienstag'],wed:[3,'Mittwoche'],thu:[4,'Donnerstag'],fri:[5,'Freitag']};
    var gui_status = {status: 1};
    var ordered_menu = null;
    var base_url = "<?php echo $this->getUrl(); ?>";
    var result_handler = {};
    var tmp_weight = null;
// func for loading js container
require(['jquery'], function($) {
    jQuery(document).ready(function () {
//        if(session.length == 0 ) {
            jQuery("#product_diy_container table tr").each(function () {
                var index = jQuery(this).attr('index');
                order_container["var_" + index] = jQuery(this).attr("sku");
                if(jQuery(this).attr("sku") === 'disable'){
                    order_container.amount = order_container.amount + 1;
                }
            });
        var customerId = '<?php echo $this->_customerSession->getCustomerId(); ?>';
        if(customerId === ""){
            $("button[class*='gui_change_']").hide();
        }
        // console.log(order_container);
    });
    /*
     update json "order container" when loading new product
     */
//    jQuery("tr[class*='price_class_']").attrchange({
//        trackValues: true,
//        callback: function (event) {
//            var index = jQuery(this).attr('index');
//            if(parseInt(index) > order_container.amount){
//                return false;
//            }
//            order_container["var_" + index] = jQuery(this).attr("sku");
//        }
//    });

    /*
    save tmp user choose in Session
     */
//    jQuery(window).bind('beforeunload',function(){
//
//        var data_to_post = "";
//        jQuery.each(order_container, function (key, value) {
//            if((key == "amount") || (value == "")){return;}
//            data_to_post = data_to_post + value + ",";
//        });
//        var postData = new FormData();
//        postData.append("user_choose", data_to_post);
//        jQuery.ajax({
//            type: "POST",
//            url: base_url+"menue/index/Session",
//            data: postData,
//            contentType: false,
//            processData: false,
//            dataType: "text",
//            success: function(data){}
//        });
//    });


});
    function load_new_var_product(sku, name, description, price, img, position) {
        require(['jquery'], function($){
        var target_block = jQuery("tr[index='"+position+"']");
            target_block.attr("sku",sku);
            target_block.find("td.img_container img").attr(
                {
                    src: img,
                    srcset: img,
                    alt: name
                });
            target_block.find("td.img_container h5").html(name);
            target_block.find("td.product_info div.product_content span").html(description);
            target_block.find("td.product_price span").html(price);
        });
        return true;
    }

    function menuStatus(element, isSideMenu = false) {
        require(['jquery'], function($) {
            var currentStatus = $(element).hasClass('active');
            var currentIndex =  $(element).parent().parent().attr('index');
            if (currentStatus){
                if(!isSideMenu){
                    if(order_container.amount >= 2){
                        return alert('Sie sollten ESSEN mindestens für drei Tage bestellen!');
                    }
                    order_container.amount = order_container.amount + 1;
                }
                $(element).parent().parent().css("background-color", "grey");
                $(element).removeClass('active');
                $(element).css('background-color', 'green');
                $(element).html('Enable');
                $(element).parent().parent().find('td.product_info')
                    .find('button').first().html("<del>Austausch</del>").prop('disabled', true);
                $(element).parent().parent().find('td.product_info').find('div.list_container').hide();
                order_container['var_'+currentIndex] = 'disable';
            }else {
                if(!isSideMenu){
                    order_container.amount = order_container.amount - 1;
                }
                $(element).parent().parent().css("background-color", "white");
                $(element).css('background-color', 'white');
                $(element).addClass('active');
                $(element).html('Disable');
                $(element).parent().parent().find('td.product_info')
                    .find('button').first().html("Austausch").prop('disabled', false);
                $(element).parent().parent().find('td.product_info').find('div.list_container').show();
                order_container['var_'+currentIndex] = $(element).parent().parent().attr('sku');
            }
        });
    }

    function menuChange(element) {
        require(['jquery'], function($) {
            jQuery(element).parent().find("div.list_container div.product_list").slideToggle();
        });
    }

    function loadTargetGUI(element) {
        require(['jquery'], function($) {
//            $(element).applyBindings();
            var loading = "<center><img src='<?php echo $this->getViewFileUrl('Nextorder_Menue::img/loading.gif'); ?>' alt='loading' style='width: 200px'/></center>";
            var currentGuiStatus = gui_status.status;
            var currentAction = $(element).attr("action");
            if(currentAction === "forwards"){
                var newStatus = currentGuiStatus + 1;
            }else{
                var newStatus = currentGuiStatus - 1;
            }
            if(newStatus === 0){ // route to view the orders from the last week
                // save ordered menu before routing
                ordered_menu = $("#product_diy_container").html();
                $("#product_diy_container").html(loading);
                $("#menu_week").html("");
                $("#order_date").html("<?php echo $this->getOrderDate(false)['begin'] ." Bis ". $this->getOrderDate(false)['end']; ?>");
                $("button.gui_change_backwards").hide();
                $("button.gui_change_forwards").show();
                var postData = new FormData();
                postData.append("begin", "<?php echo $this->getOrderDate(false)['raw_begin']; ?>");
                postData.append("end", "<?php echo $this->getOrderDate(false)['raw_end']; ?>");
                postData.append("skus_in_stock", "<?php echo $this->_inStockSkus; ?>");
                $.ajax({
                    type: "POST",
                    url: base_url+"menue/index/order",
                    data: postData,
                    contentType: false,
                    processData: false,
                    dataType: "text",
                success: function(data){
                    $("#product_diy_container").html($.parseHTML(data));
                }
                });
                gui_status.status = 0;
            }else if(newStatus === 1){ // route to view for the next week
                $("#product_diy_container").html(loading);
                $("#menu_week").html("Bestellen Sie Speisen für <b>die nächste Woche</b>");
                $("#order_date").html("<?php echo $this->getOrderDate(true)['begin'] ." Bis ". $this->getOrderDate(true)['end']; ?>");
                $("#product_diy_container").html(ordered_menu);
                $("button.gui_change_backwards").show();
                $("button.gui_change_forwards").hide();
                gui_status.status = 1;
            }else{
                return false;
            }
        });
    }

    function chooseVariant(element) {
            require(['jquery'], function($) {
                var sku = jQuery(element).find("input.sku").val();
                var name = jQuery(element).find("input.name").val()
                var description = jQuery(element).find("input.description").val();
                var img = jQuery(element).find("input.img").val();
                var price = jQuery(element).find("input.price").val();
                var position = jQuery(element).find("input.menu_index").val();
                order_container["var_" + position] = sku;
                load_new_var_product(sku, name, description, price, img, position);
            });
    }

    function guiChange(element) {
        require(['jquery'], function($) {
            switch ($(element).val()){
                case 'last':
                    $("#in_essbar").hide();
                    $("#last_order").toggle('show');
                    break;
                case 'live':
                    $("#last_order").hide();
                    $("#in_essbar").toggle('show');
                    break;
            }
        });
    }

    function menuCheck(weight) {
        require(['jquery', 'jquery/ui', 'Magento_Ui/js/modal/modal'], function($) {
//            var loading = "<center><img src='<?php //echo $this->getViewFileUrl('Nextorder_Menue::img/loading.gif'); ?>//' alt='loading' style='width: 200px'/></center>";
//            $("#diy_table").html(loading);
            var postData = new FormData();
            var data_to_post = "";
            var isSidemenuDisplay = $("#side_dish_title").css('display');
            var index = 0;
            $.each(order_container, function (key, value) {
                if((isSidemenuDisplay === 'none') && (index > 5)){
                    data_to_post = data_to_post + 'disable,';
                    index++;
                    return;
                }
                index++;
                if(key == "amount"){return;}
                data_to_post = data_to_post + value + ",";
            });
            postData.append("orders", data_to_post.substring(0, data_to_post.length -1));
            postData.append("weight", weight);
            $.ajax({
                type: "POST",
                url: base_url+"menue/validate/index",
                data: postData,
                contentType: false,
                processData: false,
                dataType: "text",
                success: function(data){
                    data = $.parseJSON(data);
                    if(data.result !== 'correct'){
                        var options = {
                            title: 'Bessermittag',
                            autoOpen: true,
                            responsive: true,
                            closed: function () {
                                console.log("modal closed");
                            },
                            buttons: [
                                {
                                text: 'Bestellung Updaten',
                                class: 'menu_update',
                                click: function () {
                                    this.closeModal();
                                    renderOrderUpdate();
//                                    $("#product_diy_additional").show();
//                                    $("#product_diy_additional_dessert").show();
                                    }
                                },
                                {
                                    text: 'Trotzdem auf Warenkorb gehen',
                                    class: 'menu_ignore',
                                    click: function () {
                                        this.closeModal();
                                        toCart();
                                    }
                                }
                            ]
                        };
                        $('<div />').html(generateErrorReport(data)).modal(options);
                    }else {
                        toCart();
                    }
                   // console.log(data);
                }
            });
        });
    }

    function weightValidate() {
        require(['jquery', 'jquery/ui', 'Magento_Ui/js/modal/modal'], function($) {
            var result = null;
            var isLoggedIn = "<?php echo $this->_isloggedIn; ?>";
            var withGoal = "<?php echo $this->getNutritionGoalLabel()[0]; ?>";
            if(!isLoggedIn || !withGoal){
                return toCart();
            }
        var weightModalOptions = {
            title: 'Bessermittag',
            autoOpen: true,
            responsive: true,
            closed: function () {
                console.log("Weight closed");
                return false;
            },
            buttons: [
                {
                    text: 'Weiter',
                    class: 'menu_gohead',
                    click: function () {
                        this.closeModal();
                        tmp_weight = $("#weight").val();
                        return menuCheck(tmp_weight);
                    }
                }
            ]
        };
            var prevWeight = '<?php echo $this->getFormatedWeight(); ?>';
        if((tmp_weight === null) || (tmp_weight === prevWeight)){
            var weightToRender = prevWeight;
        }else {
            var weightToRender = tmp_weight;
        }
            var weightForm = "<h3>Bitte bestellen Sie Ihr Körpergewicht(kg) hier</h3>" +
            "<form id='popup_form'>" +
            "<label for='weight'>Körpergewicht(kg)</label>" +
            "<input id='weight' type='text' value='"+weightToRender+"'/>" +
            "</form>";
        $('<div />').html(weightForm).modal(weightModalOptions);
    })};
    function generateErrorReport(error) {
        result_handler = {
            complement: [false, {mon:[],tue:[],wed:[],thu:[],fri:[]}],
            reload: [false, {mon:[],tue:[],wed:[],thu:[],fri:[]}]
        };
            var report = '<h3>Ihr Ernährungsziel: '+ error.goal.toUpperCase()+'</h3>' +
                '<b style="color: #0A246A">Tipps:</b> Anklicken <b>Bestellung Updaten unten,</b><ul>' +
                '<li>werden die Speisen nach den nicht erfüllten Bedingungen re-geladen.</li>' +
                '<li>Nicht ausreichende Nährstoffe können Sie durch Vor- und Nachspeise ergänzen.</li></ul><ul>';
            if(error.type === 'overall'){
                for(var key in error.report){
                    report = report + '<li style="color: #0A246A">'+
                        error.report[key].label+' '+error.report[key].operator+' <b style="color: green">'+error.report[key].required
                        +' '+error.report[key].unit+' </b>ist erwünscht. (Ihr '+ error.report[key].label +': <b style="color: red">'+ error.report[key].error_value +' '+error.report[key].unit+'</b>)</li>';
                    prepareErrorHandler(error.report[key]);
                }
            }else {
                 for(var day in error.report){
                    report = report + '<li><h5>'+week[day][1]+'</h5><ul>';
                     for(var key in error.report[day]){ // error report of each day
                         if(error.report[day][key].error_value === null){continue;}
                         report = report + '<li style="color: #0A246A">'+
                             error.report[day][key].label+' '+error.report[day][key].operator+' <b style="color: green">'+error.report[day][key].required
                             +' '+error.report[day][key].unit+'</b> ist erwünscht. (Ihre aktuelle Bestellung enthält '+ error.report[day][key].label +': <b style="color: red">'+ error.report[day][key].error_value +' '+error.report[day][key].unit+'</b>)</li>';
                         prepareErrorHandler(error.report[day][key], day);
                     }
                     report = report + '</ul></li>';
                 }
            }
            report = report + '</ul>';
        console.log(result_handler);
        return report;
    }

    function prepareErrorHandler(error, day) {
        switch (error.handler) {
            case 'complement':
                result_handler.complement[0] = true;
                result_handler.complement[1][day].push({
                    attr: error.attr,
                    label: error.label,
                    operator: error.operator,
                    required: error.required,
                    value: error.error_value,
                    unit: error.unit
                });
                break;
            case 'reload':
                result_handler.reload[0] = true;
                result_handler.reload[1][day].push({
                    attr: error.attr,
                    label: error.label,
                    operator: error.operator,
                    required: error.required,
                    value: error.error_value,
                    unit: error.unit
                });
                break;
            default:
                break;
        }
    }

    function renderOrderUpdate() {
        require(['jquery'], function($) {
            if(result_handler.complement[0] === true){
                $.each(result_handler.complement[1], function (key, value) {
                    var index_before = week[key][0] + 5;
                    var index_after = week[key][0] + 10;
                    if(value.length === 0){
                        $("#before").find("tr[index='"+index_before+"']").find("div.reload_comment").html('');
                        $("#after").find("tr[index='"+index_after+"']").find("div.reload_comment").html('');
                        return;
                    }
                    var comment = "<h5>Ergänzen Sie fehlende Ernährungsstoffe zu Ihrem Ernährungsziel für "+ week[key][1] +" hier</h5><ul>";
                    for(var i in value){
                        comment = comment + "<li>"+value[i].label+" "+value[i].operator+" "+value[i].required+" "+value[i].unit+" ist erwünscht.<span style='color: #710909'>(Letzte Prüfung: "+value[i].value+" "+value[i].unit+" bestellt)</span></li>";
                    }
                    comment = comment + "</ul>";
                    $("#before").find("tr[index='"+index_before+"']").find("div.reload_comment").html(comment);
                    $("#after").find("tr[index='"+index_after+"']").find("div.reload_comment").html(comment);
                });
                $("#side_dish_title").show();
                $("#before").show();
            }
            if(result_handler.reload[0] === true){
                $.each(result_handler.reload[1], function (key, value) {
                    var index = week[key][0];
                    if(value.length === 0){ $("#diy_table").find("tr[index='"+index+"']").find("div.reload_comment").html('');return;}
                   var comment = "<h5>Die Produkte sind wieder geladen nach den den folgenden Bedingungen</h5><ul>";
                   for(var i in value){
                       comment = comment + "<li>"+value[i].label+" "+value[i].operator+" "+value[i].required+" "+value[i].unit+"</li>";
                   }
                    comment = comment + "</ul>";
                   $("#diy_table").find("tr[index='"+index+"']").find("div.reload_comment").html(comment);

                    /**
                     * Todo: ajax reload product collection for each day
                     */
                    var postData = new FormData();
                    var conditions = {index: index, conditions: value};
                    postData.append("conditions", JSON.stringify(conditions));
                    postData.append("skus", $("#diy_table").find("tr[index='"+index+"']").find("input.allowed_skus").val());
                    $.ajax({
                        type: "POST",
                        url: base_url+"menue/validate/reload",
                        data: postData,
                        contentType: false,
                        processData: false,
                        dataType: "text",
                        success: function(data){
//                            console.log(data);
                            $("#diy_table").find("tr[index='"+index+"']").find("div.product_list").html(data);
                        }
                    });
                });

                return true
            }
            return console.log('Error Handler: NONE');
        });
    }
    function toCart() {
        require(['jquery'], function($) {
            var data_to_post = "";
            var isSidemenuDisplay = $("#side_dish_title").css('display');
            var index = 0;
            $.each(order_container, function (key, value) {
                if((isSidemenuDisplay === 'none') && (index > 5)){
                    data_to_post = data_to_post + 'disable,';
                    index++;
                    return;
                }
                index++;
                if(key == "amount"){return;}
                data_to_post = data_to_post + value + ",";
            });
            var postData = new FormData();
            postData.append("menu_orders", data_to_post.substring(0, data_to_post.length -1));
            $.ajax({
                type: "POST",
                url: base_url+"menue/index/cart",
                data: postData,
                contentType: false,
                processData: false,
                dataType: "text",
                success: function(data){
//                    if (confirm("Ihr Wochenmenu ist bereits auf Warenkorb gelegt. Wollen Sie auf Warenkorb gehen?")) {
                        window.location = base_url+"checkout/cart/";
//                    }
                }
            });
        });
    }

    function renderSideMenu(element) {
        require(['jquery'], function($) {
            var targetMenu = $(element).attr('class');
            var currentStatus = side_menu_status.render;
            if(targetMenu != currentStatus){
                $("#"+currentStatus).hide(1000);
                $("#"+targetMenu).show(1000);
                side_menu_status.render = targetMenu;
                side_menu_status.hide = currentStatus;
            }else {
                return false;
            }
        });
    }
</script>
