
<h1 id="menu_week">Bestellen Sie Speisen für <b>die nächste Woche</b></h1>
<h1><center>
        <button class="gui_change_backwards" action="backwards" onclick="loadTargetGUI(this)">
            <b style="color: blue"><     </b>
        </button>
        <b id="order_date">
            <?php echo $this->getOrderDate(true)['begin'] ." Bis ". $this->getOrderDate(true)['end']; ?>
        </b>
        <button class="gui_change_forwards" action="forwards" onclick="loadTargetGUI(this)" style="display: none">
            <b style="color: blue">     ></b>
        </button>
</center></h1>
<div id="product_diy_container">
    <table id="diy_table" border="1">
        <?php echo $this->loadProductHtmlBySku(); ?>
    </table>
    <hr />
    <table id="product_diy_additional" border="1" style="display: none">
        <h2><b>Vor- und Nachspeisen</b></h2>
        <?php echo $this->loadProductHtmlBySku(true); ?>
    </table>
    <hr />
    <center><button id="to_cart" class="action primary" onclick="menuCheck()">Weiter</button></center>
</div>
<script type="text/javascript">
    var order_container = {"amount": 0, "var_1":"", "var_2":"", "var_3":"", "var_4":"", "var_5":""};
    var gui_status = {status: 1};
    var ordered_menu = null;
    var base_url = "<?php echo $this->getUrl(); ?>";
// func for loading js container
require(['jquery'], function($) {
    jQuery(document).ready(function () {
//        if(session.length == 0 ) {
            jQuery("#product_diy_container table tr").each(function () {
                var index = jQuery(this).attr('index');
                order_container["var_" + index] = jQuery(this).attr("sku");
                if(jQuery(this).attr("sku") === 'disable'){
                    order_container.amount = order_container.amount + 1;
                }
            });
        var customerId = '<?php echo $this->_customerSession->getCustomerId(); ?>';
        if(customerId === ""){
            $("button[class*='gui_change_']").hide();
        }
        console.log(order_container);
    });
    /*
     update json "order container" when loading new product
     */
//    jQuery("tr[class*='price_class_']").attrchange({
//        trackValues: true,
//        callback: function (event) {
//            var index = jQuery(this).attr('index');
//            if(parseInt(index) > order_container.amount){
//                return false;
//            }
//            order_container["var_" + index] = jQuery(this).attr("sku");
//        }
//    });

    /*
    save tmp user choose in Session
     */
//    jQuery(window).bind('beforeunload',function(){
//
//        var data_to_post = "";
//        jQuery.each(order_container, function (key, value) {
//            if((key == "amount") || (value == "")){return;}
//            data_to_post = data_to_post + value + ",";
//        });
//        var postData = new FormData();
//        postData.append("user_choose", data_to_post);
//        jQuery.ajax({
//            type: "POST",
//            url: base_url+"menue/index/Session",
//            data: postData,
//            contentType: false,
//            processData: false,
//            dataType: "text",
//            success: function(data){}
//        });
//    });


});
    /**
     *  load new product in menu block
     * @param sku
     * @param name
     * @param description
     * @param price
     * @param img
     * @param position
     * @returns {boolean}
     */
    function load_new_var_product(sku, name, description, price, img, position) {
        require(['jquery'], function($){
        var target_block = jQuery("tr[index='"+position+"']");
            target_block.attr("sku",sku);
            target_block.find("td.img_container img").attr(
                {
                    src: img,
                    srcset: img,
                    alt: name
                });
            target_block.find("td.img_container h5").html(name);
            target_block.find("td.product_info div.product_content span").html(description);
            target_block.find("td.product_price span").html(price);
        });
        return true;
    }

    function menuStatus(element, isSideMenu = false) {
        require(['jquery'], function($) {
            var currentStatus = $(element).hasClass('active');
            var currentIndex =  $(element).parent().parent().attr('index');
            if (currentStatus){
                if(!isSideMenu){
                    if(order_container.amount >= 2){
                        return alert('Sie sollten ESSEN mindestens für drei Tage bestellen!');
                    }
                    order_container.amount = order_container.amount + 1;
                }
                $(element).parent().parent().css("background-color", "grey");
                $(element).removeClass('active');
                $(element).css('background-color', 'green');
                $(element).html('Enable');
                $(element).parent().parent().find('td.product_info')
                    .find('button').first().html("<del>Austausch</del>").prop('disabled', true);
                $(element).parent().parent().find('td.product_info').find('div.list_container').hide();
                order_container['var_'+currentIndex] = 'disable';
            }else {
                if(!isSideMenu){
                    order_container.amount = order_container.amount - 1;
                }
                $(element).parent().parent().css("background-color", "white");
                $(element).css('background-color', 'white');
                $(element).addClass('active');
                $(element).html('Disable');
                $(element).parent().parent().find('td.product_info')
                    .find('button').first().html("Austausch").prop('disabled', false);
                $(element).parent().parent().find('td.product_info').find('div.list_container').show();
                order_container['var_'+currentIndex] = $(element).parent().parent().attr('sku');
            }
        });
    }

    function menuChange(element) {
        require(['jquery'], function($) {
            jQuery(element).parent().find("div.list_container div.product_list").slideToggle();
        });
    }

    function loadTargetGUI(element) {
        require(['jquery'], function($) {
//            $(element).applyBindings();
            var loading = "<center><img src='<?php echo $this->getViewFileUrl('Nextorder_Menue::img/loading.gif'); ?>' alt='loading' style='width: 200px'/></center>";
            var currentGuiStatus = gui_status.status;
            var currentAction = $(element).attr("action");
            if(currentAction === "forwards"){
                var newStatus = currentGuiStatus + 1;
            }else{
                var newStatus = currentGuiStatus - 1;
            }
            if(newStatus === 0){ // route to view the orders from the last week
                // save ordered menu before routing
                ordered_menu = $("#product_diy_container").html();
                $("#product_diy_container").html(loading);
                $("#menu_week").html("");
                $("#order_date").html("<?php echo $this->getOrderDate(false)['begin'] ." Bis ". $this->getOrderDate(false)['end']; ?>");
                $("button.gui_change_backwards").hide();
                $("button.gui_change_forwards").show();
                var postData = new FormData();
                postData.append("begin", "<?php echo $this->getOrderDate(false)['raw_begin']; ?>");
                postData.append("end", "<?php echo $this->getOrderDate(false)['raw_end']; ?>");
                postData.append("skus_in_stock", "<?php echo $this->_inStockSkus; ?>");
                $.ajax({
                    type: "POST",
                    url: base_url+"menue/index/order",
                    data: postData,
                    contentType: false,
                    processData: false,
                    dataType: "text",
                success: function(data){
                    $("#product_diy_container").html($.parseHTML(data));
                }
                });
                gui_status.status = 0;
            }else if(newStatus === 1){ // route to view for the next week
                $("#product_diy_container").html(loading);
                $("#menu_week").html("Bestellen Sie Speisen für <b>die nächste Woche</b>");
                $("#order_date").html("<?php echo $this->getOrderDate(true)['begin'] ." Bis ". $this->getOrderDate(true)['end']; ?>");
                $("#product_diy_container").html(ordered_menu);
                $("button.gui_change_backwards").show();
                $("button.gui_change_forwards").hide();
                gui_status.status = 1;
            }else{
                return false;
            }
        });
    }

    function chooseVariant(element) {
            require(['jquery'], function($) {
                var sku = jQuery(element).find("input.sku").val();
                var name = jQuery(element).find("input.name").val()
                var description = jQuery(element).find("input.description").val();
                var img = jQuery(element).find("input.img").val();
                var price = jQuery(element).find("input.price").val();
                var position = jQuery(element).find("input.menu_index").val();
                order_container["var_" + position] = sku;
                load_new_var_product(sku, name, description, price, img, position);
            });
    }

    function guiChange(element) {
        require(['jquery'], function($) {
            switch ($(element).val()){
                case 'last':
                    $("#in_essbar").hide();
                    $("#last_order").toggle('show');
                    break;
                case 'live':
                    $("#last_order").hide();
                    $("#in_essbar").toggle('show');
                    break;
            }
        });
    }

    function menuCheck() {
        var isLoggedIn = "<?php echo $this->_isloggedIn; ?>";
        if(!isLoggedIn){
            return toCart();
        }
        require(['jquery', 'jquery/ui', 'Magento_Ui/js/modal/modal'], function($) {
//            var loading = "<center><img src='<?php //echo $this->getViewFileUrl('Nextorder_Menue::img/loading.gif'); ?>//' alt='loading' style='width: 200px'/></center>";
//            $("#diy_table").html(loading);
            var postData = new FormData();
            var data_to_post = "";
            $.each(order_container, function (key, value) {
                if(key == "amount"){return;}
                data_to_post = data_to_post + value + ",";
            });
            data_to_post = data_to_post.substring(0, data_to_post.length -1);
            postData.append("mainOrders", data_to_post);
            postData.append("sideOrders", null);
            $.ajax({
                type: "POST",
                url: base_url+"index.php/menue/validate/index",
                data: postData,
                contentType: false,
                processData: false,
                dataType: "text",
                success: function(data){
                    data = $.parseJSON(data);
                    if(data.result != 'correct'){
                        var options = {
                            title: 'Bessermittag',
                            autoOpen: true,
                            responsive: true,
                            closed: function () {
                                console.log("modal closed");
                            },
                            buttons: [
                                {
                                text: 'Bestellung Updaten',
                                class: 'menu_update',
                                click: function () {
                                    this.closeModal();
                                    $("#product_diy_additional").show();
                                    }
                                },
                                {
                                    text: 'Trotzdem auf Warenkorb gehen',
                                    class: 'menu_ignore',
                                    click: function () {
                                        this.closeModal();
                                        toCart();
                                    }
                                }
                            ]
                        };
                        $('<div />').html("<h2>"+data.message+"</h2>").modal(options);
                    }else {
                        toCart();
                    }
                }
            });
        });
    }

    function toCart() {
        require(['jquery'], function($) {
            var data_to_post = "";
            var isSidemenuDisplay = $("#product_diy_additional").css('display');
            var index = 0;
            jQuery.each(order_container, function (key, value) {
                if((isSidemenuDisplay === 'none') && (index > 5)){
                    data_to_post = data_to_post + 'disable,';
                    index++;
                    return;
                }
                index++;
                if(key == "amount"){return;}
                data_to_post = data_to_post + value + ",";
            });
            data_to_post = data_to_post.substring(0, data_to_post.length -1);
            var postData = new FormData();
            postData.append("menu_orders", data_to_post);
            console.log(data_to_post);
            jQuery.ajax({
                type: "POST",
                url: base_url+"index.php/menue/index/cart",
                data: postData,
                contentType: false,
                processData: false,
                dataType: "text",
                success: function(data){
//                    if (confirm("Ihr Wochenmenu ist bereits auf Warenkorb gelegt. Wollen Sie auf Warenkorb gehen?")) {
                        window.location = base_url+"checkout/cart/";
//                    }
                }
            });
        });
    }
</script>
