<select id="gui_select" onchange="guiChange(this)">
    <option value="last">Bestellung Für Diese Woche</option>
    <option value="live">Live Essbar Für Diese Woche</option>
</select>
<div id="last_order">
    <table>
        <tr>
            <td><h1>Sie haben für <b>diese Woche</b> bestellt</h1></td>
        </tr>
        <tr>
            <td><?php echo $this->getOrderItems();?></td>
        </tr>
        <tr><td><h3>Bestellung am <?php echo $this->_orderDate;?></h3></td></tr>
    </table>
</div>
<div id="in_essbar" style="display: none">
    <table>
        <tr>
            <td><h1><span style="color: green;">Live</span> Essbar für <b>diese Woche</b></h1></td>
        </tr>
        <tr>
            <td>
                <?php
                    $liveSkus = $this->getLiveSkus();
                    $this->getChildBlock('LiveListProduct')->setLiveSkus($liveSkus);
                ?>
                <?php echo $this->getChildHtml('LiveListProduct',false); ?>
            </td>
        </tr>
    </table>
</div>
<script type="text/javascript">

</script>
